name: Triage tasks

on:
  pull_request:
  pull_request_target:

concurrency:
  group: "triage-${{ github.event.pull_request.number }}-${{ github.event_name }}"
  cancel-in-progress: true

jobs:
  triage:
    if: |
      github.event_name == 'pull_request_target' &&
      github.event.pull_request.user.type != 'Bot' &&
      github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - name: Label pull request
        uses: Homebrew/actions/label-pull-requests@fc695c54c2032716dd4cedd007489c8e32fc8a5d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          def: |
            - label: new formula
              status: added
              path: Formula/.+
              allow_any_match: true

            - label: new cask
              status: added
              path: Casks/.+
              allow_any_match: true

            - label: linux-only
              path: Formula/.+
              content: depends_on :linux

            - label: macos-only
              path: Formula/.+
              content: depends_on :macos

            - label: agents.md
              path: (AGENTS|CLAUDE)\.md
              allow_any_match: true

            - label: autobump
              path: \.github/autobump\.txt
              allow_any_match: true

            - label: skills
              path: skills/.+
              allow_any_match: true

            - label: missing license
              path: Formula/.+
              missing_content: \n  license .+\n

            - label: deprecated license
              path: Formula/.+
              content: license .*"(GPL|LGPL|AGPL|GFDL)-[0-9].[0-9][+]?".*

            - label: boost
              path: Formula/.+
              content: depends_on "boost(@[0-9.]+)?"

            - label: ffmpeg
              path: Formula/.+
              content: depends_on "ffmpeg(@[0-9.]+)?"

            - label: go
              path: Formula/.+
              content: depends_on "go(@[0-9.]+)?"

            - label: haskell
              path: Formula/.+
              content: depends_on "(ghc|haskell-stack)(@[0-9.]+)?"

            - label: icu4c
              path: Formula/.+
              content: depends_on "icu4c(@[0-9.]+)?"

            - label: java
              path: Formula/.+
              content: depends_on "openjdk(@[0-9.]+)?"

            - label: linux-only
              path: Formula/.+
              content: depends_on :linux

            - label: macos-only
              path: Formula/.+
              content: depends_on :macos

            - label: lua
              path: Formula/.+
              content: depends_on "(lua|luajit|luajit-openresty)(@[0-9.]+)?"

            - label: nodejs
              path: Formula/.+
              content: depends_on "node(@[0-9.]+)?"

            - label: ocaml
              path: Formula/.+
              content: depends_on "ocaml(@[0-9.]+)?"

            - label: perl
              path: Formula/.+
              content: (depends_on|uses_from_macos) "perl(@[0-9.]+)?"

            - label: php
              path: Formula/.+
              content: (depends_on|uses_from_macos) "php(@[0-9.]+)?"

            - label: python
              path: Formula/.+
              content: (depends_on|uses_from_macos) "python(@[0-9.]+)?"
              missing_content: (depends_on|uses_from_macos) "python(@[0-9.]+)?" => \[?:(build|test)

            - label: ruby
              path: Formula/.+
              content: (depends_on|uses_from_macos) "ruby(@[0-9.]+)?"

            - label: rust
              path: Formula/.+
              content: depends_on "rust(@[0-9.]+)?"

            - label: zig
              path: Formula/.+
              content: depends_on "zig(@[0-9.]+)?"

            - label: dotnet
              path: Formula/.+
              content: depends_on "dotnet(@[0-9.]+)?"

            - label: swift
              path: Formula/.+
              content: system "swift", "build"

            - label: alias
              path: Aliases/.+
              allow_any_match: true

            - label: shell-completion
              path: Formula/.+
              patch_content: (generate_completions_from_executable|bash_completion|zsh_completion|fish_completion|pwsh_completion)

  typos:
    name: Spell Check
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b # v1.50.1
        with:
          files: .
